config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check\
  # root to: redirect('/')
  root to: 'home#index'

  get '/', to: 'home#index'
  # Defines the root path route ("/")
  # root "posts#index"
  resources :transactions
  resources :accounts, only: %i[index new show create edit update delete] do
    # member do
    #   patch :index
    # end

    # collection do
    #   get :fees_edit
    # end
  end
end

app/models/account.rb
class Account < ApplicationRecord
  # Validations
  validates :name, presence: true
  validates :balance, numericality: { only_integer: true }
  validates :user_id, presence: true

  # Associations
  belongs_to :user
  has_many :transactions

  # Additional methods and logic can be added here
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  # Validations
  validates :name, presence: true
  validates :balance, :prev_bala, :amount, numericality: { only_integer: true }
  validates :account_id, :type_id, :user_id, presence: true
  before_validation :set_transaction_date

  # Associations
  belongs_to :account
  belongs_to :transaction_type, foreign_key: 'type_id'
  belongs_to :user


  private

  def set_transaction_date
    self.transaction_date ||= Date.today
  end

  # Additional methods and logic can be added here
end

app/models/transaction_type.rb
class TransactionType < ApplicationRecord
  # Validations
  validates :name, presence: true

  # Associations
  has_many :transactions

  # Additional methods and logic can be added here
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :accounts
  has_many :transactions


  def self.current=(user)
    Thread.current[:current_user] = user
  end

  def self.current
    Thread.current[:current_user]
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!  # Ensure user is authenticated

  # GET /accounts
  def index
    @accounts = current_user.accounts  # Assuming accounts are associated with the current user
  end

  # GET /accounts/1
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # POST /accounts
  def create
    @account = current_user.accounts.build(account_params)  # Build account for the current user

    if @account.save
      redirect_to @account, notice: 'Account was successfully created.'
    else
      render :new
    end
  end

  # GET /accounts/1/edit
  def edit
  end

  # PATCH/PUT /accounts/1
  def update
    if @account.update(account_params)
      redirect_to @account, notice: 'Account was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /accounts/1
  def destroy
    @account.destroy
    redirect_to accounts_url, notice: 'Account was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:name, :description, :branch, :account_type, :balance)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  around_action :set_current_user

  def set_current_user
    User.current = current_user
    yield
  rescue Exception => e
    raise e
  ensure
    User.current = nil
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:edit, :update, :destroy]
  before_action :set_accounts, only: [:new, :edit, :create, :update]

  # GET /transactions
  def index
    @transactions = Transaction.where(user_id: current_user.id)
  end

  # GET /transactions/:id
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/:id/edit
  def edit
  end

  # POST /transactions
  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.user_id = current_user.id
    account = Account.find(@transaction.account_id)
    @transaction.prev_bala = account.balance
    case @transaction.type_id
    when 1 # Assuming 1 means 'Credit'
      account.balance += @transaction.amount
    when 2 # Assuming 2 means 'Debit'
      account.balance -= @transaction.amount
    end
    @transaction.balance = account.balance
    respond_to do |format|
      if @transaction.save
        account.save # Save the updated account balance
        format.html { redirect_to transactions_path, notice: 'Transaction was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /transactions/:id
  def update
    old_amount = @transaction.amount
    respond_to do |format|
      if @transaction.update(transaction_params)
        revert_account_balance(@transaction, old_amount)
        update_account_balance(@transaction)
        format.html { redirect_to transactions_path, notice: 'Transaction was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /transactions/:id
  def destroy
    revert_account_balance(@transaction, @transaction.amount)
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_path, notice: 'Transaction was successfully deleted.' }
    end
  end

  private

  # Method to set transaction for certain actions
  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  # Method to get the available accounts
  def set_accounts
    @accounts = Account.where(user_id: current_user.id)
  end

  # Method to update the account balance after a transaction
  def update_account_balance(transaction)
    account = Account.find(transaction.account_id)
    if transaction.type_id == 1 # Assuming type_id 1 = deposit
      account.update(balance: account.balance + transaction.amount)
    else
      account.update(balance: account.balance - transaction.amount)
    end
  end

  # Method to revert the account balance when a transaction is updated or deleted
  def revert_account_balance(transaction, old_amount)
    account = Account.find(transaction.account_id)
    if transaction.type_id == 1 # Assuming type_id 1 = deposit
      account.update(balance: account.balance - old_amount)
    else
      account.update(balance: account.balance + old_amount)
    end
  end

  # Strong parameters for transactions
  def transaction_params
    params.require(:transaction).permit(:name, :account_id, :balance, :amount, :type_id, :notes, :user_id)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>
      <ul>
        <% account.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field mb-3">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  <div class="field mb-3">
    <%= form.label :description, class: 'form-label' %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>
  <div class="field mb-3">
    <%= form.label :branch, class: 'form-label' %>
    <%= form.text_field :branch, class: 'form-control' %>
  </div>
  <div class="field mb-3">
    <%= form.label :balance, class: 'form-label' %>
    <%= form.number_field :balance, class: 'form-control' %>
  </div>
  <div class="actions mb-2 d-flex justify-content-center">
    <%= form.submit action, class: "btn btn-primary submit-btn"%>
    <%= link_to 'Back', path, class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/accounts/create.html.erb
<h1>Accounts#create</h1>
<p>Find me in app/views/accounts/create.html.erb</p>

app/views/accounts/destroy.html.erb
<h1>Accounts#destroy</h1>
<p>Find me in app/views/accounts/destroy.html.erb</p>

app/views/accounts/edit.html.erb
<h1>Edit Account</h1>
<%= render partial: 'form', locals: { account: @account, action: 'Update', path: accounts_path } %>

app/views/accounts/index.html.erb
<h1>Accounts</h1>
<%= link_to 'Create New Account', new_account_path, class: 'btn btn-primary mb-3' %>
<div class="accounts-table-wrapper">
  <table id="accounts_table" class="table" data-behavior="basic_tables">
    <thead>
      <tr>
        <th>S/No</th>
        <th>Name</th>
        <th>Description</th>
        <th>Branch</th>
        <th>Balance</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @accounts.each do |account| %>
        <tr>
          <td><%= account.id %></td>
          <td><%= account.name %></td>
          <td><%= account.description %></td>
          <td><%= account.branch %></td>
          <td><%= account.balance %></td>
          <td>
            <%= link_to 'Edit', edit_account_path(account), class: 'btn btn-outline-primary' %>
            <%= link_to 'Delete', account, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/accounts/new.html.erb
<h1>New Account</h1>
<%= render partial: 'form', locals: { account: @account, action: 'Create', path: accounts_path } %>

app/views/accounts/show.html.erb
<h1>Account Details</h1>
<p>
  <strong>Name:</strong>
  <%= @account.name %>
</p>
<p>
  <strong>Description:</strong>
  <%= @account.description %>
</p>
<p>
  <strong>Branch:</strong>
  <%= @account.branch %>
</p>
<p>
  <strong>Balance:</strong>
  <%= @account.balance %>
</p>
<%= link_to 'Edit', edit_account_path(@account), class: 'btn btn-primary' %>
<%= link_to 'Back', accounts_path, class: 'btn btn-secondary' %>

app/views/accounts/update.html.erb
<h1>Accounts#update</h1>
<p>Find me in app/views/accounts/update.html.erb</p>

app/views/home/index.html.erb
<div class="home_page">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AkBanking</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
</head>
<body>
  <%= render "shared/header"%>
  <% if request.path == root_path %>
    <%= yield %>
  <% else %>
    <div class="container">
      <%= yield %>
    </div>
  <% end %>
</body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg w-100 <%= request.path == root_path ? 'position-absolute' : 'navbar-dark bg-dark' %>">
  <div class="container-fluid d-flex justify-content-space-between">
    <a class="navbar-brand text-light" href="<%= root_path %>">AK</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active  text-light" aria-current="page" href="<%= root_path %>">Home</a>
        </li>
        <li class="nav-item">
          <%= link_to 'Transactions', transactions_path, class: 'nav-link text-light'  %>
        </li>
        <li class="nav-item">
          <%= link_to 'Transact', new_transaction_path, class: 'nav-link text-light'  %>
        </li>
        <li class="nav-item">
          <%= link_to 'My Accounts', accounts_path, class: 'nav-link text-light' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Add Account', new_account_path, class: 'nav-link text-light' %>
        </li>
        <li class="nav-item">
          <a class="nav-link  text-light" href="#" tabindex="-1" aria-disabled="true">Profile</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/transactions/_grouped_transactions.html.erb
<% groouped_transactions = transactions.group_by { |transaction| transaction.account.name  } %>
<div class="accordion grouped-table grouped-table-wrapper" id="accordionPanelsStayOpenExample">
  <% groouped_transactions.each do |account, transactions| %>
    <div class="accordion-item">
      <h2 class="accordion-header" id="<%= account.parameterize %>_head">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#<%= account.parameterize %>_target" aria-expanded="false" aria-controls="<%= account.parameterize %>_target">
          <%=  account.capitalize %>
        </button>
      </h2>
      <div id="<%= account.parameterize %>_target" class="accordion-collapse collapse show" aria-labelledby="<%= account.parameterize %>_head">
        <div class="accordion-body">
          <table id="transaction_table_<%= account %>" class="table" data-behavior="basic_tables">
            <%= render partial: 'thead' %>
            <tbody>
              <% transactions.each do |transaction| %>
                <%= render partial: 'tbody', locals: {transaction: transaction} %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/transactions/_tbody.html.erb
<tr>
  <td><%= transaction.name %></td>
  <td><%= transaction.account.name %></td>
  <td><%= transaction.amount %></td>
  <td><%= transaction.prev_bala %></td>
  <td><%= transaction.balance %></td>
  <td><%= transaction.transaction_type.description %></td>
  <td><%= transaction.notes %></td>
  <td>
    <%= link_to 'Edit', edit_transaction_path(transaction), class: 'btn btn-outline-primary'  %>
    <%= link_to 'Delete', transaction, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger' %>
  </td>
</tr>

app/views/transactions/_thead.html.erb
<thead>
  <tr>
    <th data-sortable="true">Name</th>
    <th data-sortable="true">Account</th>
    <th data-sortable="true">Amount</th>
    <th data-sortable="true">Prev Balance</th>
    <th data-sortable="true">Current Balance</th>
    <th data-sortable="true">Type</th>
    <th data-sortable="true">Note</th>
    <th data-sortable="true">Actions</th>
  </tr>
</thead>

app/views/transactions/_ungrouped_transactions.html.erb
<div class="ungroup-table-wrapper">
  <table id="transaction_table" class="table ungrouped-table" data-behavior="basic_tables">
    <%= render partial: 'thead' %>
    <tbody>
      <% transactions.each do |transaction| %>
        <%= render partial: 'tbody', locals: {transaction: transaction} %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/transactions/edit.html.erb
<h1><%= action_name.capitalize %> Transaction</h1>
<%= form_with(model: @transaction, local: true) do |form| %>
  <div>
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  <div>
    <%= form.label :account_id, "Account", class: 'form-label' %>
    <%= form.collection_select :account_id, @accounts, :id, :name, class: 'form-control' %>
  </div>
  <div>
    <%= form.label :amount, class: 'form-label' %>
    <%= form.number_field :amount, class: 'form-control' %>
  </div>
  <div>
    <%= form.label :type_id, "Transaction Type", class: 'form-label' %>
    <%= form.collection_select :type_id, TransactionType.all, :id, :name, class: 'form-control' %>
  </div>
  <div>
    <%= form.label :notes, class: 'form-label' %>
    <%= form.text_area :notes, class: 'form-control' %>
  </div>
  <div class="actions mt-2 mb-2 d-flex justify-content-center">
    <%= form.submit "Update", class: "btn btn-primary submit-btn"  %>
    <%= link_to 'Back', transactions_path, class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/transactions/index.html.erb
<div class="d-inline">
  <h1>Your Transactions</h1>
  <%= link_to 'New Transaction', new_transaction_path, class: 'btn btn-success' %>
</div>
<% if @transactions.present? %>
  <div class="trans-table-container">
    <div class="form-check form-switch"  id='group'>
      <input class="form-check-input" type="checkbox" role="switch" id="group_transactions" data-behavior="group_transaction">
      <label class="form-check-label" for="group_transactions">Group by Account</label>
    </div>
    <div>
      <%= render partial: 'ungrouped_transactions', locals: {transactions: @transactions} %>
      <%= render partial: 'grouped_transactions', locals: {transactions: @transactions} %>
    </div>
  </div>
<% else %>
  <h6>No Transactions Found</h6>
<% end %>

app/views/transactions/new.html.erb
<h1><%= action_name.capitalize %> Transaction</h1>
<%= form_with(model: @transaction, local: true) do |form| %>
  <div>
    <%= form.label :name, class: 'form-label'%>
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  <div>
    <%= form.label :account_id, "Account", class: 'form-label' %>
    <%= form.collection_select :account_id, @accounts, :id, :name, class: 'form-control' %>
  </div>
  <div>
    <%= form.label :amount, class: 'form-label' %>
    <%= form.number_field :amount, class: 'form-control' %>
  </div>
  <div>
    <%= form.label :type_id, "Transaction Type", class: 'form-label' %>
    <%= form.collection_select :type_id, TransactionType.all, :id, :name, class: 'form-select"' %>
  </div>
  <div>
    <%= form.label :notes, class: 'form-label' %>
    <%= form.text_area :notes, class: 'form-control' %>
  </div>
  <div class="actions mb-2 mt-4   d-flex justify-content-center">
    <%= form.submit 'Create', class: "btn btn-primary submit-btn"%>
    <%= link_to 'Back', transactions_path, class: 'btn btn-secondary' %>
  </div>
<% end %>